#runtime: python
runtime: custom # for gcloud app deploy for dockerfile
api_version: 1
env: flex
#entrypoint: uvicorn -b $PORT server:app -w 4 -k uvicorn.workers.UvicornWorker
entrypoint: gunicorn -b $PORT server:app

runtime_config:
        python_version: 3

manual_scaling:
        instances: 1

resources:
        cpu: 2
        memory_gb: 4
        disk_size_gb: 10
        
