version: "3"
services:
    web:
        images: doxxitxxyoung/glit_server:latest
#        images: alexandero85/demo-stuff:part1
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 100M
                restart_policy:
                    condition: on-failure
            ports:
                - "80:80"
            networks:
                - webnet
networks:
    webnet:

